#define BT_VELOCIDAD 9600
#define VELOCIDAD_PROXIMIDAD 0.017
#define VALOR_255 255
#define VALOR_191 191
#define VALOR_126 126
#define VALOR_0 0
#define VALOR_DISTANCIA 20
#define CARACTER_T 'T'
#define CARACTER_HM 'H'
#define CARACTER_D 'D'
#define CARACTER_Z 'z'
#define CARACTER_X 'x'
#define CARACTER_Y 'y'
#define CARACTER_U 'u'
#define CARACTER_V 'v'
#define CARACTER_W 'w'
#define CARACTER_A 'a'
#define CARACTER_B 'b'
#define CARACTER_C 'c'
#define CARACTER_E 'e'
#define CARACTER_G 'g'
#define CARACTER_H 'h'
#define CARACTER_I 'i'
#define CARACTER_J 'j'
#define CARACTER_K 'k'
#define CARACTER_L 'l'
#define CARACTER_N 'n'
#define CARACTER_P 'p'
#define CARACTER_Q 'q'
#define CARACTER_R 'r'
